/*
 *SCRIPT CREACIÓN:
 *alter session set "_oracle_script"=true;
 *create user enrique_macdonals identified by enrique_macdonals;
 *GRANT CONNECT, RESOURCE, DBA TO enrique_macdonals;
 *
 *AUTOR: ENRIQUE LIMONES
 *FECHA: 15/1/2026
 *GRUPO: Daniel, Álvaro, Javier, Luis Enrique y Denise
 *Descripción: Creación de una base de datos para generar reservas en la cadena de restaurantes "Macdonals"
 *
 *ATAJOS: CTRL + H (BUSCAR, CAMBIAR Y REEMPLAZAR)
 **/

CREATE TABLE RESTAURANTE(
NOMBRE VARCHAR2(9) NOT NULL,
CONSTRAINT PK_RESTAURANTE PRIMARY KEY (NOMBRE)
);

CREATE TABLE CLIENTES(
NOMBRE VARCHAR2(50) NOT NULL,
CORREO VARCHAR2(50),-- UNIQUE, -- PARA QUE NO PUEDAN INTRODUCIRSE CORREOS REPETIDOS
TELEFONO VARCHAR2(20) NOT NULL,
DIRECCION VARCHAR2(100),
NOMBRE_RESTAURANTE VARCHAR2(9) NOT NULL,
CONSTRAINT PK_CLIENTES PRIMARY KEY (NOMBRE),
CONSTRAINT UQ_CLIENTES_CORREO UNIQUE (CORREO), -- DE PREFERIA ESTA OPCION ES MÁS VISUAL
CONSTRAINT FK_CLIENTES_RESTAURANTE FOREIGN KEY (NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE)
);

CREATE TABLE RESERVAS(
CODIGO NUMBER(10) NOT NULL,
NUM_PERSONA NUMBER(3),
ZONA VARCHAR2(50),
FECHA DATE,
HORA DATE,
NOMBRE VARCHAR2(50) NOT NULL,
CONSTRAINT PK_RESERVAS PRIMARY KEY (CODIGO),
CONSTRAINT FK_RESERVAS_CLIENTES FOREIGN KEY (NOMBRE) REFERENCES CLIENTES(NOMBRE)
);

CREATE TABLE EMPLEADOS(
DNI VARCHAR2(20) NOT NULL, -- MODELO INTERNACIONAL EN MEXICO POR EJEMPLO LLEGA A 20 CARACTERES
ROL VARCHAR2(50),
NOMBRE VARCHAR2(50),
SUELDO NUMBER(10,2), -- HASTA 10 DIGITOS CON 2 DECIMALES
EMAIL VARCHAR2(50),
DIRECCION VARCHAR2(100),
TELEFONO VARCHAR2(20), -- PARA GUARDAR ESPACIOS Y PREFIJOS
CUENTA_BANCARIA VARCHAR2(34), -- 24 ES EL ESTANDAR PERO 34 EN CASO DE CUENTAS INTERNACIONALES
NOMBRE_RESTAURANTE VARCHAR2(9) NOT NULL,
CONSTRAINT PK_EMPLEADOS PRIMARY KEY (DNI),
CONSTRAINT UQ_EMPLEADOS UNIQUE (EMAIL),
CONSTRAINT FK_EMPLEADOS_RESTAURANTE FOREIGN KEY (NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE)
);

CREATE TABLE COCINEROS(
DNI VARCHAR2(20) NOT NULL,
GRADO_COCINA VARCHAR2(20),
CONSTRAINT PK_COCINEROS PRIMARY KEY (DNI),
CONSTRAINT FK_COCINEROS_EMPLEADOS FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE CAMAREROS(
DNI VARCHAR2(20) NOT NULL,
ANIOS_TRABAJADOS NUMBER(2),
CONSTRAINT PK_CAMAREROS PRIMARY KEY (DNI),
CONSTRAINT FK_CAMAREROS_EMPLEADOS FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE MESAS(
NUMERO NUMBER(2) NOT NULL,
CODIGO NUMBER(10) NOT NULL,
DNI VARCHAR2(20) NOT NULL,
CONSTRAINT PK_MESAS PRIMARY KEY (NUMERO),
CONSTRAINT FK1_MESAS_RESERVAS FOREIGN KEY (CODIGO) REFERENCES RESERVAS(CODIGO),
CONSTRAINT FK2_MESAS_CAMAREROS FOREIGN KEY (DNI) REFERENCES CAMAREROS(DNI)
);

CREATE TABLE RECETAS(
CODIGO NUMBER(10) NOT NULL,
ALERGENOS VARCHAR2(20) NOT NULL,
TIPO VARCHAR2(20) NOT NULL,
CONSTRAINT PK_RECETAS PRIMARY KEY (CODIGO)
);

CREATE TABLE COCINAN(
DNI VARCHAR2(20) NOT NULL,
CODIGO NUMBER(10) NOT NULL,
CONSTRAINT PK_COCINAN PRIMARY KEY (DNI),
CONSTRAINT FK1_COCINAN_COCINEROS FOREIGN KEY (DNI) REFERENCES COCINEROS(DNI),
CONSTRAINT FK2_COCINAN_RECETAS FOREIGN KEY (CODIGO) REFERENCES RECETAS(CODIGO)
);

CREATE TABLE PRODUCTOS(
ID VARCHAR2(50) NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL,
PRECIO NUMBER (10,2) NOT NULL,
STOCK NUMBER NOT NULL,
CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID)
);

CREATE TABLE CONSUMEN(
CODIGO_RECETA NUMBER(10) NOT NULL,
ID VARCHAR2(50) NOT NULL,
CONSTRAINT PK_CONSUMEN PRIMARY KEY (CODIGO_RECETA, ID),
CONSTRAINT FK1_CONSUMEN_RECETAS FOREIGN KEY (CODIGO_RECETA) REFERENCES RECETAS(CODIGO),
CONSTRAINT FK2_CONSUMEN_PRODUCTOS FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID)
);

CREATE TABLE PROVEEDORES(
CIF VARCHAR2(20) NOT NULL,
NOMBRE VARCHAR2(20) NOT NULL,
DESCUENTO NUMBER(3) NOT NULL,
FIABILIDAD VARCHAR2(20),
CUENTA_BANCARIA VARCHAR2(34) NOT NULL,
CONSTRAINT PK_PROVEEDORES PRIMARY KEY(CIF)
);

CREATE TABLE SON_COMPRADOS(
ID VARCHAR2(50) NOT NULL,
CIF VARCHAR2(20) NOT NULL,
CONSTRAINT PK_SON_COMPRADOS PRIMARY KEY (ID, CIF),
CONSTRAINT FK1_SON_COMPRADOS_PRODUCTOS FOREIGN KEY (ID) REFERENCES PRODUCTOS (ID),
CONSTRAINT FK2_SON_COMPRADOS_PROVEEDORES FOREIGN KEY (CIF) REFERENCES PROVEEDORES (CIF)
);


