/*alter session set "_oracle_script"=true;  
create user ejercicioclase identified by ejercicioclase;
GRANT CONNECT, RESOURCE, DBA TO ejercicioclase;*/


CREATE TABLE RESTAURANTE
(
NOMBRE_RESTAURANTE VARCHAR2(25),
CONSTRAINT PK_RESTAURANTE PRIMARY KEY(NOMBRE_RESTAURANTE)
);

CREATE TABLE CLIENTES
(
NOMBRE_CLIENTE VARCHAR2(25),
CORREO VARCHAR2(30),
TELEFONO NUMBER(9),
DIRECCION VARCHAR2(30),
NOMBRE_RESTAURANTE VARCHAR2(25),
CONSTRAINT PK_CLIENTES PRIMARY KEY(NOMBRE_CLIENTE),
CONSTRAINT FK_CLIENTES FOREIGN KEY(NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE_RESTAURANTE)
);

CREATE TABLE RESERVAS
(
CODIGO NUMBER(20),
N_PERSONAS NUMBER(10),
ZONA VARCHAR2(30),
FECHA DATE,
HORA DATE,
NOMBRE_CLIENTE VARCHAR2(25),
CONSTRAINT PK_RESERVAS PRIMARY KEY(CODIGO),
CONSTRAINT FK_RESERVAS FOREIGN KEY(NOMBRE_CLIENTE) REFERENCES CLIENTES(NOMBRE_CLIENTE)
);

CREATE TABLE EMPLEADOS
(
DNI VARCHAR2(10),
ROL VARCHAR2(20),
NOMBRE_EMPLEADO VARCHAR2(25),
SUELDO NUMBER(10),
EMAIL VARCHAR2(25),
DIRECCION VARCHAR2(30),
TELEFONO NUMBER(9),
CUENTA_BANCARIA VARCHAR2(25),
NOMBRE_RESTAURANTE VARCHAR2(25),
CONSTRAINT PK_EMPLEADOS PRIMARY KEY(DNI),
CONSTRAINT FK_EMPLEADOS FOREIGN KEY(NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE_RESTAURANTE)
);

CREATE TABLE COCINEROS
(
DNI VARCHAR2(10),
GRADO_COCINA VARCHAR2(25),
CONSTRAINT PK_COCINEROS PRIMARY KEY(DNI),
CONSTRAINT FK_COCINEROS FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE CAMAREROS
(
DNI VARCHAR2(10),
AÑOS_TRABAJADOS NUMBER(20),
CONSTRAINT PK_CAMAREROS PRIMARY KEY(DNI),
CONSTRAINT FK_CAMAREROS FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE MESAS
(
NUMERO NUMBER(20),
CODIGO NUMBER(20),
DNI VARCHAR2(10),
CONSTRAINT PK_MESAS PRIMARY KEY(NUMERO),
CONSTRAINT FK1_MESAS FOREIGN KEY(CODIGO) REFERENCES RESERVAS(CODIGO),
CONSTRAINT FK2_MESAS FOREIGN KEY(DNI) REFERENCES CAMAREROS(DNI)
);

CREATE TABLE RECETAS
(
CODIGO_RECETAS NUMBER(20),
ALERGENOS VARCHAR2(25),
TIPO VARCHAR2(25),
CONSTRAINT PK_RECETAS PRIMARY KEY(CODIGO_RECETAS)
);

CREATE TABLE COCINAN
(
DNI VARCHAR2(10),
CODIGO_RECETAS NUMBER(20),
CONSTRAINT PK_COCINAN PRIMARY KEY(DNI,CODIGO_RECETAS),
CONSTRAINT FK1_COCINAN FOREIGN KEY(DNI) REFERENCES COCINEROS(DNI),
CONSTRAINT FK2_COCINAN FOREIGN KEY(CODIGO_RECETAS) REFERENCES RECETAS(CODIGO_RECETAS)
);

CREATE TABLE PRODUCTOS
(
ID_PRODUCTOS NUMBER(25),
NOMBRE VARCHAR2(25),
PRECIO NUMBER(25),
STOCK NUMBER(25),
CONSTRAINT PK_PRODUCTOS PRIMARY KEY(ID_PRODUCTOS)
);

CREATE TABLE CONSUMEN
(
CODIGO_RECETAS NUMBER(20),
ID_PRODUCTOS NUMBER(25),
CONSTRAINT PK_CONSUMEN PRIMARY KEY(CODIGO_RECETAS,ID_PRODUCTOS),
CONSTRAINT FK1_CONSUMEN FOREIGN KEY(CODIGO_RECETAS) REFERENCES RECETAS(CODIGO_RECETAS),
CONSTRAINT FK2_CONSUMEN FOREIGN KEY(ID_PRODUCTOS) REFERENCES PRODUCTOS(ID_PRODUCTOS)
);

CREATE TABLE PROVEEDORES
(
CIF NUMBER(20),
NOMBRE VARCHAR2(25),
DESCUENTO NUMBER(20),
FIABILILDAD VARCHAR2(25),
CUENTA_BANCARIA VARCHAR2(25),
CONSTRAINT PK_PROVEEDORES PRIMARY KEY(CIF)
);

CREATE TABLE SON_COMPRADOS
(
ID_PRODUCTOS NUMBER(25),
CIF NUMBER(20),
CONSTRAINT PK_SON_COMPRADOS PRIMARY KEY(ID_PRODUCTOS,CIF),
CONSTRAINT FK1_SON_COMPRADOS FOREIGN KEY(ID_PRODUCTOS) REFERENCES PRODUCTOS(ID_PRODUCTOS),
CONSTRAINT FK2_SON_COMPRADOS FOREIGN KEY(CIF) REFERENCES PROVEEDORES(CIF)
);



















