/*create database ejercicioClaseSQL;
create user 'dummy'@'%' identified by 'dummy';
grant all on db_exampleName.* to 'dummy'@'%';*/

CREATE TABLE RESTAURANTE 
(
NOMBRE_RESTAURANTE VARCHAR(25),
CONSTRAINT PK_RESTAURANTE PRIMARY KEY(NOMBRE_RESTAURANTE)
);

CREATE TABLE CLIENTES
(
NOMBRE_CLIENTE VARCHAR(25),
CORREO VARCHAR(30),
TELEFONO NUMERIC(9),
DIRECCION VARCHAR(30),
NOMBRE_RESTAURANTE VARCHAR(25),
CONSTRAINT PK_CLIENTES PRIMARY KEY(NOMBRE_CLIENTE),
CONSTRAINT FK_CLIENTES FOREIGN KEY(NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE_RESTAURANTE)
);

CREATE TABLE RESERVAS
(
CODIGO NUMERIC(20),
N_PERSONAS NUMERIC(10),
ZONA VARCHAR(30),
FECHA DATE,
HORA DATE,
NOMBRE_CLIENTE VARCHAR(25),
CONSTRAINT PK_RESERVAS PRIMARY KEY(CODIGO),
CONSTRAINT FK_RESERVAS FOREIGN KEY(NOMBRE_CLIENTE) REFERENCES CLIENTES(NOMBRE_CLIENTE)
);

CREATE TABLE EMPLEADOS
(
DNI VARCHAR(10),
ROL VARCHAR(20),
NOMBRE_EMPLEADO VARCHAR(25),
SUELDO NUMERIC(10),
EMAIL VARCHAR(25),
DIRECCION VARCHAR(30),
TELEFONO NUMERIC(9),
CUENTA_BANCARIA VARCHAR(25),
NOMBRE_RESTAURANTE VARCHAR(25),
CONSTRAINT PK_EMPLEADOS PRIMARY KEY(DNI),
CONSTRAINT FK_EMPLEADOS FOREIGN KEY(NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE_RESTAURANTE)
);

CREATE TABLE COCINEROS
(
DNI VARCHAR(10),
GRADO_COCINA VARCHAR(25),
CONSTRAINT PK_COCINEROS PRIMARY KEY(DNI),
CONSTRAINT FK_COCINEROS FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE CAMAREROS
(
DNI VARCHAR(10),
AÑOS_TRABAJADOS NUMERIC(20),
CONSTRAINT PK_CAMAREROS PRIMARY KEY(DNI),
CONSTRAINT FK_CAMAREROS FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE MESAS
(
NUMERO NUMERIC(20),
CODIGO NUMERIC(20),
DNI VARCHAR(10),
CONSTRAINT PK_MESAS PRIMARY KEY(NUMERO),
CONSTRAINT FK1_MESAS FOREIGN KEY(CODIGO) REFERENCES RESERVAS(CODIGO),
CONSTRAINT FK2_MESAS FOREIGN KEY(DNI) REFERENCES CAMAREROS(DNI)
);

CREATE TABLE RECETAS
(
CODIGO_RECETAS NUMERIC(20),
ALERGENOS VARCHAR(25),
TIPO VARCHAR(25),
CONSTRAINT PK_RECETAS PRIMARY KEY(CODIGO_RECETAS)
);

CREATE TABLE COCINAN
(
DNI VARCHAR(10),
CODIGO_RECETAS NUMERIC(20),
CONSTRAINT PK_COCINAN PRIMARY KEY(DNI,CODIGO_RECETAS),
CONSTRAINT FK1_COCINAN FOREIGN KEY(DNI) REFERENCES COCINEROS(DNI),
CONSTRAINT FK2_COCINAN FOREIGN KEY(CODIGO_RECETAS) REFERENCES RECETAS(CODIGO_RECETAS)
);

CREATE TABLE PRODUCTOS
(
ID_PRODUCTOS NUMERIC(25),
NOMBRE VARCHAR(25),
PRECIO NUMERIC(25),
STOCK NUMERIC(25),
CONSTRAINT PK_PRODUCTOS PRIMARY KEY(ID_PRODUCTOS)
);

CREATE TABLE CONSUMEN
(
CODIGO_RECETAS NUMERIC(20),
ID_PRODUCTOS NUMERIC(25),
CONSTRAINT PK_CONSUMEN PRIMARY KEY(CODIGO_RECETAS,ID_PRODUCTOS),
CONSTRAINT FK1_CONSUMEN FOREIGN KEY(CODIGO_RECETAS) REFERENCES RECETAS(CODIGO_RECETAS),
CONSTRAINT FK2_CONSUMEN FOREIGN KEY(ID_PRODUCTOS) REFERENCES PRODUCTOS(ID_PRODUCTOS)
);

CREATE TABLE PROVEEDORES
(
CIF NUMERIC(20),
NOMBRE VARCHAR(25),
DESCUENTO NUMERIC(20),
FIABILILDAD VARCHAR(25),
CUENTA_BANCARIA VARCHAR(25),
CONSTRAINT PK_PROVEEDORES PRIMARY KEY(CIF)
);

CREATE TABLE SON_COMPRADOS
(
ID_PRODUCTOS NUMERIC(25),
CIF NUMERIC(20),
CONSTRAINT PK_SON_COMPRADOS PRIMARY KEY(ID_PRODUCTOS,CIF),
CONSTRAINT FK1_SON_COMPRADOS FOREIGN KEY(ID_PRODUCTOS) REFERENCES PRODUCTOS(ID_PRODUCTOS),
CONSTRAINT FK2_SON_COMPRADOS FOREIGN KEY(CIF) REFERENCES PROVEEDORES(CIF)
);