/*
CREATE DATABASE MACDONALS;
CREATE USER 'dummy'@'%' IDENTIFIED BY 'dummy';
GRANT ALL ON B2EJ3.* TO 'dummy'@'%';
*/

CREATE TABLE RESTAURANTE
(
	NOMBRE VARCHAR(30),
	CONSTRAINT PK_RESTAURANTE PRIMARY KEY (NOMBRE)
);
CREATE TABLE CLIENTES
(
	NOMBRE VARCHAR(30),
	CORREO VARCHAR(50),
	TELEFONO NUMERIC(10),
	DIRECCION VARCHAR(30),
	NOMBRE_RESTAURANTE VARCHAR(30),
	CONSTRAINT PK_CLIENTES PRIMARY KEY (NOMBRE),
	CONSTRAINT FK1_CLIENTES FOREIGN KEY (NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE)

);
CREATE TABLE RESERVAS
(
	CODIGO NUMERIC(10),
	NUMERO_PERSONA NUMERIC(10),
	ZONA VARCHAR(30),
	FECHA DATE,
	HORA DATE,
	NOMBRE VARCHAR(30),
	CONSTRAINT PK_RESERVAS PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_RESERVAS FOREIGN KEY (NOMBRE) REFERENCES CLIENTES(NOMBRE)
);
CREATE TABLE EMPLEADOS
(
	DNI VARCHAR(10),
	ROL VARCHAR(10),
	NOMBRE VARCHAR(30),
	SUELDO NUMERIC(10),
	EMAIL VARCHAR(10),
	DIRECCION VARCHAR(50),
	TELEFONO NUMERIC(10),
	CUENTA_BANCARIA VARCHAR(10),
	NOMBRE_RESTAURANTE VARCHAR(30),
	CONSTRAINT PK_EMPLEADOS PRIMARY KEY (DNI),
	CONSTRAINT FK1_EMPLEADOS FOREIGN KEY (NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE)
);
CREATE TABLE COCINEROS
(
	DNI VARCHAR(10),
	GRADO_COCINA VARCHAR(10),
	CONSTRAINT PK_COCINEROS PRIMARY KEY (DNI),
	CONSTRAINT FK1_COCINEROS FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
);
CREATE TABLE CAMAREROS
(
	DNI VARCHAR(10),
	ANIOS_TRABAJADOS NUMERIC(10),
	CONSTRAINT PK_CAMAREROS PRIMARY KEY (DNI),
	CONSTRAINT FK1_CAMAREROS FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
);
CREATE TABLE MESAS
(
	NUMERO NUMERIC(10),
	CODIGO NUMERIC(10),
	DNI VARCHAR(10),
	CONSTRAINT PK_MESAS PRIMARY KEY (NUMERO),
	CONSTRAINT FK1_MESAS FOREIGN KEY (CODIGO) REFERENCES RESERVAS(CODIGO),
	CONSTRAINT FK2_MESAS FOREIGN KEY (DNI) REFERENCES CAMAREROS(DNI)
);
CREATE TABLE RECETAS
(
	CODIGO NUMERIC(10),
	ALERGENOS VARCHAR(10),
	TIPO VARCHAR(10),
	CONSTRAINT PK_RECETAS PRIMARY KEY (CODIGO)
);
CREATE TABLE COCINAN
(
	DNI VARCHAR(10),
	CODIGO NUMERIC(10),
	CONSTRAINT PK_COCINAN PRIMARY KEY (DNI, CODIGO),
	CONSTRAINT FK1_COCINAN FOREIGN KEY (DNI) REFERENCES COCINEROS(DNI),
	CONSTRAINT FK2_COCINAN FOREIGN KEY (CODIGO) REFERENCES RECETAS(CODIGO)
);
CREATE TABLE PRODUCTOS
(
	ID NUMERIC(10),
	NOMBRE VARCHAR(30),
	PRECIO NUMERIC(10,2),
	STOCK NUMERIC(10),
	CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID)
);
CREATE TABLE CONSUMEN
(
	CODIGO_RECETAS NUMERIC(10),
	ID NUMERIC(10),
	CONSTRAINT PK_CONSUMEN PRIMARY KEY (CODIGO_RECETAS, ID),
	CONSTRAINT FK1_CONSUMEN FOREIGN KEY (CODIGO_RECETAS) REFERENCES RECETAS(CODIGO),
	CONSTRAINT FK2_CONSUMEN FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID)
);
CREATE TABLE PROVEEDORES
(
	CIF NUMERIC (10),
	NOMBRE VARCHAR(30),
	DESCUENTO NUMERIC(10,2),
	FIABILIDAD VARCHAR(10),
	CUENTA_BANCARIA VARCHAR(10),
	CONSTRAINT PK_PROVEEDORES PRIMARY KEY (CIF)
);
CREATE TABLE SON_COMPRADOS
(
	ID NUMERIC(10),
	CIF NUMERIC(10),
	CONSTRAINT PK_SON_COMPRADOS PRIMARY KEY (ID, CIF),
	CONSTRAINT FK1_SON_COMPRADOS FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID),
	CONSTRAINT FK2_SON_COMPRADOS FOREIGN KEY (CIF) REFERENCES PROVEEDORES(CIF)
);