/* Creación esquema:
create database EJMACDONALS;
create user 'dummy@'%' identified by 'dummy';
grant all on db_exampleName.* to 'dummy'@'%';*/

CREATE TABLE RESTAURANTE
(
NOMBRE VARCHAR(30),
CONSTRAINT PK_RESTAURANTE PRIMARY KEY(NOMBRE)
);

CREATE TABLE CLIENTES
(
NOMBRE VARCHAR(30),
CORREO VARCHAR(30),
TELEFONO NUMERIC(9),
DIRECCION VARCHAR(30),
NOMBRE_RESTAURANTE VARCHAR(30),
CONSTRAINT PK_CLIENTES PRIMARY KEY(NOMBRE),
CONSTRAINT FK_CLIENTES FOREIGN KEY(NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE)
);

CREATE TABLE RESERVAS
(
CODIGO NUMERIC(20),
N_PERSONAS NUMERIC(10),
ZONA VARCHAR(30),
FECHA DATE,
HORA DATE,
NOMBRE_CLIENTE VARCHAR(30),
CONSTRAINT PK_RESERVAS PRIMARY KEY(CODIGO),
CONSTRAINT FK_RESERVAS FOREIGN KEY(NOMBRE_CLIENTE) REFERENCES CLIENTES(NOMBRE)
);

CREATE TABLE EMPLEADOS
(
DNI VARCHAR(10),
ROL VARCHAR(20),
NOMBRE_EMPLEADO VARCHAR(30),
SUELDO NUMERIC(10),
EMAIL VARCHAR(30),
DIRECCION VARCHAR(30),
TELEFONO NUMERIC(9),
CUENTA_BANCARIA VARCHAR(30),
NOMBRE_RESTAURANTE VARCHAR(30),
CONSTRAINT PK_EMPLEADOS PRIMARY KEY(DNI),
CONSTRAINT FK_EMPLEADOS FOREIGN KEY(NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE)
);

CREATE TABLE COCINEROS
(
DNI VARCHAR(10),
GRADO_COCINA VARCHAR(30),
CONSTRAINT PK_COCINEROS PRIMARY KEY(DNI),
CONSTRAINT FK_COCINEROS FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE CAMAREROS
(
DNI VARCHAR(10),
ANOS_TRABAJADOS NUMERIC(20),
CONSTRAINT PK_CAMAREROS PRIMARY KEY(DNI),
CONSTRAINT FK_CAMAREROS FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE MESAS
(
NUMERO NUMERIC(20),
CODIGO NUMERIC(20),
DNI VARCHAR(10),
CONSTRAINT PK_MESAS PRIMARY KEY(NUMERO),
CONSTRAINT FK1_MESAS FOREIGN KEY(CODIGO) REFERENCES RESERVAS(CODIGO),
CONSTRAINT FK2_MESAS FOREIGN KEY(DNI) REFERENCES CAMAREROS(DNI)
);

CREATE TABLE RECETAS
(
CODIGO NUMERIC(20),
ALERGENOS VARCHAR(25),
TIPO VARCHAR(25),
CONSTRAINT PK_RECETAS PRIMARY KEY(CODIGO)
);

CREATE TABLE COCINAN
(
DNI VARCHAR(10),
CODIGO_RECETAS NUMERIC(20),
CONSTRAINT PK_COCINAN PRIMARY KEY(DNI,CODIGO_RECETAS),
CONSTRAINT FK1_COCINAN FOREIGN KEY(DNI) REFERENCES COCINEROS(DNI),
CONSTRAINT FK2_COCINAN FOREIGN KEY(CODIGO_RECETAS) REFERENCES RECETAS(CODIGO)
);

CREATE TABLE PRODUCTOS
(
ID NUMERIC(20),
NOMBRE VARCHAR(30),
PRECIO NUMERIC(25),
STOCK NUMERIC(25),
CONSTRAINT PK_PRODUCTOS PRIMARY KEY(ID)
);

CREATE TABLE CONSUMEN
(
CODIGO_RECETAS NUMERIC(20),
ID_PRODUCTOS NUMERIC(20),
CONSTRAINT PK_CONSUMEN PRIMARY KEY(CODIGO_RECETAS,ID_PRODUCTOS),
CONSTRAINT FK1_CONSUMEN FOREIGN KEY(CODIGO_RECETAS) REFERENCES RECETAS(CODIGO),
CONSTRAINT FK2_CONSUMEN FOREIGN KEY(ID_PRODUCTOS) REFERENCES PRODUCTOS(ID)
);

CREATE TABLE PROVEEDORES
(
CIF NUMERIC(20),
NOMBRE VARCHAR(30),
DESCUENTO NUMERIC(20),
FIABILILDAD VARCHAR(30),
CUENTA_BANCARIA VARCHAR(30),
CONSTRAINT PK_PROVEEDORES PRIMARY KEY(CIF)
);

CREATE TABLE SON_COMPRADOS
(
ID_PRODUCTOS NUMERIC(30),
CIF NUMERIC(20),
CONSTRAINT PK_SON_COMPRADOS PRIMARY KEY(ID_PRODUCTOS,CIF),
CONSTRAINT FK1_SON_COMPRADOS FOREIGN KEY(ID_PRODUCTOS) REFERENCES PRODUCTOS(ID),
CONSTRAINT FK2_SON_COMPRADOS FOREIGN KEY(CIF) REFERENCES PROVEEDORES(CIF)
);