/*
 *SCRIPT CREACIÓN:
 *create database enrique_macdonals;
 *create user 'el_macdonals'@'%' identified by 'el_macdonals';
 *grant all on enrique_macdonals.* to 'el_macdonals'@'%';
 *
 *AUTOR: ENRIQUE LIMONES
 *FECHA: 15/1/2026
 *GRUPO: Daniel, Álvaro, Javier, Luis Enrique y Denise
 *Descripción: Creación de una base de datos para generar reservas en la cadena de restaurantes "Macdonals"
 *
 *ATAJOS: CTRL + H (BUSCAR, CAMBIAR Y REEMPLAZAR)
 *
 **/

CREATE TABLE RESTAURANTE(
NOMBRE VARCHAR(9) NOT NULL,
CONSTRAINT PK_RESTAURANTE PRIMARY KEY (NOMBRE)
);

CREATE TABLE CLIENTES(
NOMBRE VARCHAR(50) NOT NULL,
CORREO VARCHAR(50),-- UNIQUE, -- PARA QUE NO PUEDAN INTRODUCIRSE CORREOS REPETIDOS
TELEFONO VARCHAR(20) NOT NULL,
DIRECCION VARCHAR(100),
NOMBRE_RESTAURANTE VARCHAR(9) NOT NULL,
CONSTRAINT PK_CLIENTES PRIMARY KEY (NOMBRE),
CONSTRAINT UQ_CLIENTES_CORREO UNIQUE (CORREO), -- DE PREFERIA ESTA OPCION ES MÁS VISUAL
CONSTRAINT FK_CLIENTES_RESTAURANTE FOREIGN KEY (NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE)
);

CREATE TABLE RESERVAS(
CODIGO INT(10) NOT NULL,
NUM_PERSONA INT(3),
ZONA VARCHAR(50),
FECHA DATE,
HORA TIME,
NOMBRE VARCHAR(50) NOT NULL,
CONSTRAINT PK_RESERVAS PRIMARY KEY (CODIGO),
CONSTRAINT FK_RESERVAS_CLIENTES FOREIGN KEY (NOMBRE) REFERENCES CLIENTES(NOMBRE)
);

CREATE TABLE EMPLEADOS(
DNI VARCHAR(20) NOT NULL, -- MODELO INTERNACIONAL EN MEXICO POR EJEMPLO LLEGA A 20 CARACTERES
ROL VARCHAR(50),
NOMBRE VARCHAR(50),
SUELDO DECIMAL(10,2), -- HASTA 10 DIGITOS CON 2 DECIMALES
EMAIL VARCHAR(50),
DIRECCION VARCHAR(100),
TELEFONO VARCHAR(20), -- PARA GUARDAR ESPACIOS Y PREFIJOS
CUENTA_BANCARIA VARCHAR(34), -- 24 ES EL ESTANDAR PERO 34 EN CASO DE CUENTAS INTERNACIONALES
NOMBRE_RESTAURANTE VARCHAR(9) NOT NULL,
CONSTRAINT PK_EMPLEADOS PRIMARY KEY (DNI),
CONSTRAINT UQ_EMPLEADOS UNIQUE (EMAIL),
CONSTRAINT FK_EMPLEADOS_RESTAURANTE FOREIGN KEY (NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE)
);

CREATE TABLE COCINEROS(
DNI VARCHAR(20) NOT NULL,
GRADO_COCINA VARCHAR(20),
CONSTRAINT PK_COCINEROS PRIMARY KEY (DNI),
CONSTRAINT FK_COCINEROS_EMPLEADOS FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE CAMAREROS(
DNI VARCHAR(20) NOT NULL,
ANIOS_TRABAJADOS INT(2),
CONSTRAINT PK_CAMAREROS PRIMARY KEY (DNI),
CONSTRAINT FK_CAMAREROS_EMPLEADOS FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE MESAS(
NUMERO INT(2) NOT NULL,
CODIGO INT(10) NOT NULL,
DNI VARCHAR(20) NOT NULL,
CONSTRAINT PK_MESAS PRIMARY KEY (NUMERO),
CONSTRAINT FK1_MESAS_RESERVAS FOREIGN KEY (CODIGO) REFERENCES RESERVAS(CODIGO),
CONSTRAINT FK2_MESAS_CAMAREROS FOREIGN KEY (DNI) REFERENCES CAMAREROS(DNI)
);

CREATE TABLE RECETAS(
CODIGO INT(10) NOT NULL,
ALERGENOS VARCHAR(20) NOT NULL,
TIPO VARCHAR(20) NOT NULL,
CONSTRAINT PK_RECETAS PRIMARY KEY (CODIGO)
);

CREATE TABLE COCINAN(
DNI VARCHAR(20) NOT NULL,
CODIGO INT(10) NOT NULL,
CONSTRAINT PK_COCINAN PRIMARY KEY (DNI),
CONSTRAINT FK1_COCINAN_COCINEROS FOREIGN KEY (DNI) REFERENCES COCINEROS(DNI),
CONSTRAINT FK2_COCINAN_RECETAS FOREIGN KEY (CODIGO) REFERENCES RECETAS(CODIGO)
);

CREATE TABLE PRODUCTOS(
ID VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
PRECIO DECIMAL (10,2) NOT NULL,
STOCK INT NOT NULL,
CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID)
);

CREATE TABLE CONSUMEN(
CODIGO_RECETA INT(10) NOT NULL,
ID VARCHAR(50) NOT NULL,
CONSTRAINT PK_CONSUMEN PRIMARY KEY (CODIGO_RECETA, ID),
CONSTRAINT FK1_CONSUMEN_RECETAS FOREIGN KEY (CODIGO_RECETA) REFERENCES RECETAS(CODIGO),
CONSTRAINT FK2_CONSUMEN_PRODUCTOS FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID)
);

CREATE TABLE PROVEEDORES(
CIF VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
DESCUENTO INT(3) NOT NULL,
FIABILIDAD VARCHAR(20),
CUENTA_BANCARIA VARCHAR(34) NOT NULL,
CONSTRAINT PK_PROVEEDORES PRIMARY KEY(CIF)
);

CREATE TABLE SON_COMPRADOS(
ID VARCHAR(50) NOT NULL,
CIF VARCHAR(20) NOT NULL,
CONSTRAINT PK_SON_COMPRADOS PRIMARY KEY (ID, CIF),
CONSTRAINT FK1_SON_COMPRADOS_PRODUCTOS FOREIGN KEY (ID) REFERENCES PRODUCTOS (ID),
CONSTRAINT FK2_SON_COMPRADOS_PROVEEDORES FOREIGN KEY (CIF) REFERENCES PROVEEDORES (CIF)
);


