/*
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER MACDONALS IDENTIFIED BY MACDONALS;
GRANT CONNECT, RESOURCE, DBA TO MACDONALS;
*/

CREATE TABLE RESTAURANTE
(
	NOMBRE VARCHAR2(30),
	CONSTRAINT PK_RESTAURANTE PRIMARY KEY (NOMBRE)
);
CREATE TABLE CLIENTES
(
	NOMBRE VARCHAR2(30),
	CORREO VARCHAR2(50),
	TELEFONO NUMBER(10),
	DIRECCION VARCHAR2(30),
	NOMBRE_RESTAURANTE VARCHAR2(30),
	CONSTRAINT PK_CLIENTES PRIMARY KEY (NOMBRE),
	CONSTRAINT FK1_CLIENTES FOREIGN KEY (NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE)

);
CREATE TABLE RESERVAS
(
	CODIGO NUMBER(10),
	NUMERO_PERSONA NUMBER(10),
	ZONA VARCHAR2(30),
	FECHA DATE,
	HORA DATE,
	NOMBRE VARCHAR2(30),
	CONSTRAINT PK_RESERVAS PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_RESERVAS FOREIGN KEY (NOMBRE) REFERENCES CLIENTES(NOMBRE)
);
CREATE TABLE EMPLEADOS
(
	DNI VARCHAR2(10),
	ROL VARCHAR2(10),
	NOMBRE VARCHAR2(30),
	SUELDO NUMBER(10),
	EMAIL VARCHAR2(20),
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(10),
	CUENTA_BANCARIA VARCHAR2(10),
	NOMBRE_RESTAURANTE VARCHAR2(30),
	CONSTRAINT PK_EMPLEADOS PRIMARY KEY (DNI),
	CONSTRAINT FK1_EMPLEADOS FOREIGN KEY (NOMBRE_RESTAURANTE) REFERENCES RESTAURANTE(NOMBRE)
);
CREATE TABLE COCINEROS
(
	DNI VARCHAR2(10),
	GRADO_COCINA VARCHAR2(10),
	CONSTRAINT PK_COCINEROS PRIMARY KEY (DNI),
	CONSTRAINT FK1_COCINEROS FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
);
CREATE TABLE CAMAREROS
(
	DNI VARCHAR2(10),
	ANIOS_TRABAJADOS NUMBER(10),
	CONSTRAINT PK_CAMAREROS PRIMARY KEY (DNI),
	CONSTRAINT FK1_CAMAREROS FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
);
CREATE TABLE MESAS
(
	NUMERO NUMBER(10),
	CODIGO NUMBER(10),
	DNI VARCHAR2(10),
	CONSTRAINT PK_MESAS PRIMARY KEY (NUMERO),
	CONSTRAINT FK1_MESAS FOREIGN KEY (CODIGO) REFERENCES RESERVAS(CODIGO),
	CONSTRAINT FK2_MESAS FOREIGN KEY (DNI) REFERENCES CAMAREROS(DNI)
);
CREATE TABLE RECETAS
(
	CODIGO NUMBER(10),
	ALERGENOS VARCHAR2(10),
	TIPO VARCHAR2(10),
	CONSTRAINT PK_RECETAS PRIMARY KEY (CODIGO)
);
CREATE TABLE COCINAN
(
	DNI VARCHAR2(10),
	CODIGO NUMBER(10),
	CONSTRAINT PK_COCINAN PRIMARY KEY (DNI, CODIGO),
	CONSTRAINT FK1_COCINAN FOREIGN KEY (DNI) REFERENCES COCINEROS(DNI),
	CONSTRAINT FK2_COCINAN FOREIGN KEY (CODIGO) REFERENCES RECETAS(CODIGO)
);
CREATE TABLE PRODUCTOS
(
	ID NUMBER(10),
	NOMBRE VARCHAR2(30),
	PRECIO NUMBER(10,2),
	STOCK NUMBER(10),
	CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID)
);
CREATE TABLE CONSUMEN
(
	CODIGO_RECETAS NUMBER(10),
	ID NUMBER(10),
	CONSTRAINT PK_CONSUMEN PRIMARY KEY (CODIGO_RECETAS, ID),
	CONSTRAINT FK1_CONSUMEN FOREIGN KEY (CODIGO_RECETAS) REFERENCES RECETAS(CODIGO),
	CONSTRAINT FK2_CONSUMEN FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID)
);
CREATE TABLE PROVEEDORES
(
	CIF NUMBER (10),
	NOMBRE VARCHAR2(30),
	DESCUENTO NUMBER(10,2),
	FIABILIDAD VARCHAR2(10),
	CUENTA_BANCARIA VARCHAR2(10),
	CONSTRAINT PK_PROVEEDORES PRIMARY KEY (CIF)
);
CREATE TABLE SON_COMPRADOS
(
	ID NUMBER(10),
	CIF NUMBER(10),
	CONSTRAINT PK_SON_COMPRADOS PRIMARY KEY (ID, CIF),
	CONSTRAINT FK1_SON_COMPRADOS FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID),
	CONSTRAINT FK2_SON_COMPRADOS FOREIGN KEY (CIF) REFERENCES PROVEEDORES(CIF)
);